#!/bin/bash

deps=()

# ┌┬┐┌─┐┌─┐┬  ┌─┐
#  │ │ ││ ││  └─┐
#  ┴ └─┘└─┘┴─┘└─┘
#  tools

deps+=(git wl-clipboard brightnessctl htop btop bitwarden base-devel cmake ninja localsend ufw)

# ┌─┐┬ ┬┌─┐┬  ┬  
# └─┐├─┤├┤ │  │  
# └─┘┴ ┴└─┘┴─┘┴─┘
# shell

# deps+=(zsh fzf oh-my-zsh-git pkgfile powerline-fonts vim zsh zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-syntax-highlighting zsh-theme-powerlevel10k)

# idk this simpler
deps+=(cachyos-zsh-config)
deps+=(cachyos-fish-config starship)

# ┌┬┐┌─┐┬─┐┌┬┐┬┌┐┌┌─┐┬  
#  │ ├┤ ├┬┘│││││││├─┤│  
#  ┴ └─┘┴└─┴ ┴┴┘└┘┴ ┴┴─┘
#  terminal

deps+=(kitty alacritty)

# ┬ ┬┌┬┐
# ││││││
# └┴┘┴ ┴
# wm

deps+=(hyprland hypridle hyprlock)

# ┌┐ ┌─┐┬─┐
# ├┴┐├─┤├┬┘
# └─┘┴ ┴┴└─
# bar

deps+=(waybar)

# ┌┐┌┌─┐┌┬┐┬┌─┐┬┌─┐┌─┐┌┬┐┬┌─┐┌┐┌┌─┐
# ││││ │ │ │├┤ ││  ├─┤ │ ││ ││││└─┐
# ┘└┘└─┘ ┴ ┴└  ┴└─┘┴ ┴ ┴ ┴└─┘┘└┘└─┘
# notifications

deps+=(mako swayosd )

# ┬  ┌─┐┬ ┬┌┐┌┌─┐┬ ┬┌─┐┬─┐
# │  ├─┤│ │││││  ├─┤├┤ ├┬┘
# ┴─┘┴ ┴└─┘┘└┘└─┘┴ ┴└─┘┴└─
# launcher

deps+=(elephant elephant-desktopapplications elephant-clipboard elephant-symbols elephant-calc elephant-providerlist elephant-todo elephant-menus)
deps+=(walker)

deps+=(zen-browser-bin brave-bin)

# ┌┬┐┌─┐─┐ ┬┌┬┐  ┌─┐┌┬┐┬┌┬┐┌─┐┬─┐
#  │ ├┤ ┌┴┬┘ │   ├┤  │││ │ │ │├┬┘
#  ┴ └─┘┴ └─ ┴   └─┘─┴┘┴ ┴ └─┘┴└─
#  text editor

deps+=(vim neovim)

# ┌─┐┬┬  ┌─┐  ┌┬┐┌─┐┌┐┌┌─┐┌─┐┌─┐┬─┐
# ├┤ ││  ├┤   │││├─┤│││├─┤│ ┬├┤ ├┬┘
# └  ┴┴─┘└─┘  ┴ ┴┴ ┴┘└┘┴ ┴└─┘└─┘┴└─
# file manager

deps+=(yazi ouch util-linux starship dragon-drop)
deps+=(dolphin)


printf "%s " "${deps[@]}"
