###########
### TUI ###
###########

bindd = $mainMod, RETURN, Terminal, exec, $terminal
bindd = $mainMod SHIFT, RETURN, Terminal (float), exec, $terminal --class float-term
bindd = $mainMod, E, File manager, exec, $fileManager
bindd = $mainMod, A, Task manager (htop), exec, $terminal --class htop -e htop  # A for Activity
bindd = $mainMod SHIFT, A, Task manager (btop), exec, $terminal -e btop
bindd = $mainMod, N, Editor, exec, $terminal -e nvim
bindd = $mainMod SHIFT, N, Editor (float), exec, $terminal --class float-term -e nvim

###########
### GUI ###
###########

bindd = $mainMod, B, Browser, exec, $browser
bindd = $mainMod, SLASH, Passwords, exec, bitwarden-desktop
