#!/usr/bin/env bash

# Get the current layout
CURRENT=$(setxkbmap -query | awk '/layout/ {print $2}')

# Layouts. You can add yours.
declare -A LAYOUTS=(
  ["US English"]="us"
  ["ID Indonesia"]="id"
)

# Show rofi menu
show_rofi_menu() {
  local options=""
  for layout in "${!LAYOUTS[@]}"; do
    options+="$layout\n"
  done
  echo -e "${options%\\n}" | rofi \
    -dmenu \
    -p "Keyboard Layout" \
    -mesg "Current layout --> $CURRENT" \
    -markup-rows \
    -theme "$HOME/.config/bspwm/src/rofi-themes/Keyboard.rasi"
}

# Select and apply the layout
selected=$(show_rofi_menu)
if [[ -n "$selected" && -n "${LAYOUTS[$selected]}" ]]; then
  setxkbmap "${LAYOUTS[$selected]}"
fi
