#!/usr/bin/env bash

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
--reload-bspwm)
  bspc wm -r
  ;;
--menu)
  rofi -show drun -theme "$HOME"/.config/bspwm/src/rofi-themes/Launcher.rasi
  ;;
--rice)
  RiceSelector
  ;;
--bluetooth)
  rofi-bluetooth
  ;;
--music)
  Term --music
  ;;
--filemanager)
  thunar
  ;;
--browser)
  firefox
  ;;
  # --telegram)
  #   telegram-desktop
  #   ;;
--soundcontrol)
  pavucontrol
  ;;
--player)
  eww -c "$WIDGET_DIR" open --toggle music
  ;;
--calendar)
  eww -c "$WIDGET_DIR" open --toggle date
  ;;
*)
  echo "Invalid Option"
  ;;
esac
