#!/usr/bin/env bash

CFG_TERM="$HOME/.config/bspwm/src/.term"
DEFAULT_TERM="alacritty"
ROFI_THEME="$HOME/.config/bspwm/src/rofi-themes/TermSelector.rasi"

# Creating config file if not exists.
[ ! -f "$CFG_TERM" ] && echo "$DEFAULT_TERM" >"$CFG_TERM"

# Main var
MY_TERM=$(<"$CFG_TERM")

# Function to choose the terminal using rofi
choose_terminal() {
  local options=("Alacritty" "Kitty")
  local current_term=$(tr '[:upper:]' '[:lower:]' <"$CFG_TERM")

  local selected_index=$(printf '%s\n' "${options[@],,}" | awk -v cur="$current_term" '$0==cur {print NR-1; exit}')

  local chosen
  chosen=$(printf '%s\n' "${options[@]}" | rofi -theme "$ROFI_THEME" -mesg "[ Your current terminal is $MY_TERM ]" -dmenu -selected-row "$selected_index")

  [[ -n "$chosen" ]] && echo "${chosen,,}" >"$CFG_TERM"
}

# Terminal selector
[ "$1" = "--selecterm" ] && choose_terminal

# Launch the terminal with appropriate options
case $MY_TERM in
"alacritty")
  case $1 in
  "--terminal")
    alacritty
    ;;
  "--floating")
    alacritty --class FloaTerm,FloaTerm
    ;;
  "--scratch")
    id=$(xdotool search --class scratch)

    if [ -z "$id" ]; then
      tdrop -a -w 80% -h 50% -y 0 -x 10% --class scratch alacritty --class=scratch &
    else
      bspc node "$id" -g hidden -d focused -f
    fi
    ;;
  "--filemanager")
    alacritty -e yazi
    ;;
  "--editor")
    alacritty -e nvim
    ;;
  "--taskmanager")
    alacritty -e htop
    ;;
  "--music")
    alacritty --class FloaTerm,MusicTerm -e ncmpcpp
    ;;
  esac
  ;;
"kitty")
  case $1 in
  "--terminal")
    kitty
    ;;
  "--floating")
    kitty --class=FloaTerm
    ;;
  "--scratch")
    id=$(xdotool search --class scratch)

    if [ -z "$id" ]; then
      tdrop -a -w 80% -h 50% -y 0 -x 10% --class scratch kitty --class=scratch &
    else
      bspc node "$id" -g hidden -d focused -f
    fi
    ;;
  "--filemanager")
    kitty -e yazi
    ;;
  "--editor")
    kitty -e nvim
    ;;
  "--taskmanager")
    kitty -e htop
    ;;
  "--music")
    kitty --name=MusicTerm --class=FloaTerm -e ncmpcpp
    ;;
  esac
  ;;
esac
