#!/usr/bin/env bash

# Current rice
read -r RICETHEME <"${HOME}"/.config/bspwm/.rice

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1
export PRIMARY_DISPLAY
PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

# Default 1 monitor with 6 workspaces
for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
  bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
  #bspc monitor "$monitor" -d '' '' '' '' '' ''
done

## For two or three monitors configuration see https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules

bspc config window_gap 5
bspc config split_ratio 0.51
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
# bspc config swallow_first_click false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a scratch sticky=on state=floating focus=on

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

# Set system vars for polybar
"$HOME"/.config/bspwm/src/SetSysVars

# Launch sxhkd daemon
pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/src/config/sxhkdrc & }

# Load current theme
"${HOME}"/.config/bspwm/rices/"${RICETHEME}"/Theme.sh

# Launch picom
pidof -q picom || { picom --config "${HOME}"/.config/bspwm/src/config/picom.conf & }

# TODO: What is this?
# Launch xsettingsd
pidof -q xsettings || { xsettingsd --config="${HOME}"/.config/bspwm/src/config/xsettingsd >/dev/null 2>&1 & }

# Launch bspm for true transparent monocle
pidof -q bspm || { bspm -d & }

# Launch eww daemon
pidof -q eww || { eww -c "${HOME}"/.config/bspwm/eww daemon & }

# Launch clipboard daemon
pidof -q greenclip || { greenclip daemon & }

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# disk auto-mount
udiskie -a &

# Run xidlehook
xidlehook \
  --not-when-fullscreen \
  --timer 600 \
  "xrandr --output \"$PRIMARY_DISPLAY\" --brightness .1" \
  "xrandr --output \"$PRIMARY_DISPLAY\" --brightness 1" \
  --timer 300 \
  "xrandr --output \"$PRIMARY_DISPLAY\" --brightness 1; betterlockscreen -l" \
  "" \
  --timer 1800 \
  "systemctl suspend" \
  "" \
  &
