###################
### KEYBINDINGS ###
###################

$mainMod = SUPER

source = ./bindings/app.conf
source = ./bindings/media.conf
source = ./bindings/tiling.conf
source = ./bindings/utilities.conf

bindd = $mainMod CTRL, M, Exit Hyprland, exec, hyprland-exit
