# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ 


# ┌┬┐┌─┐┌─┐┌─┐┬ ┬┬ ┌┬┐  ┌─┐┌─┐┌─┐
#  ││├┤ ├┤ ├─┤│ ││  │   ├─┤├─┘├─┘
# ─┴┘└─┘└  ┴ ┴└─┘┴─┘┴   ┴ ┴┴  ┴  

# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = kitty
$browser = zen-browser
$fileManager = kitty -e yazi

source = ./autostart.conf
source = ./variables.conf
source = ./bindings.conf
source = ./envs.conf


# ┌┬┐┌─┐┌┐┌┬┌┬┐┌─┐┬─┐
# ││││ │││││ │ │ │├┬┘
# ┴ ┴└─┘┘└┘┴ ┴ └─┘┴└─

monitor = eDP-1, preferred, auto, 1


# ┬  ┌─┐┌─┐┬┌─  ┌┐┌  ┌─┐┌─┐┌─┐┬  
# │  │ ││ │├┴┐  │││  ├┤ ├┤ ├┤ │  
# ┴─┘└─┘└─┘┴ ┴  ┘└┘  └  └─┘└─┘┴─┘

# No transparency for browsers
# windowrule = tag +chromium-based-browser, match:class ^(brave(-browser)?|[cC]hrom(e|ium)|helium|Microsoft-edge|Vivaldi-stable)(-.+__-Default)?$
# windowrule = tag +firefox-based-browser, match:class ^([fF]irefox|zen|librewolf)(-.+__-Default)?$
# windowrule = tag +browser, match:tag chromium-based-browser
# windowrule = tag +browser, match:tag firefox-based-browser
# windowrule = opacity 1 override 0.97 override, match:tag browser

# No transparency apps
# windowrule = tag +no-transparency-apps, match:class ^(org.gnome.Evince|feh|foliate|imv|mpv|zoom)?$
# windowrule = opacity 1 override 0.97 override, match:tag no-transparency-apps

# Transparent apps
windowrule = tag +transparent-apps, match:class ^(alacritty|kitty|yazi)?$
windowrule = tag +transparent-apps, match:tag floating-window
windowrule = opacity 0.9 override 0.85 override, match:tag transparent-apps
layerrule {
  name = walker
  blur = on
  dim_around = on
  xray = on
  match:namespace = walker
}

# To replicate “smart gaps” / “no gaps when only” from other WMs/Compositors, use this bad boy:
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]

# Floating windows
windowrule = tag +floating-partial, match:class ^(blueberry.py|float-term|htop|wiremix)$
windowrule = tag +floating-window, match:tag floating-partial
windowrule = float 1, match:tag floating-window
windowrule = center 1, match:tag floating-window
windowrule = size 900 650, match:tag floating-partial

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppress_event maximize, match:class .*

# # Fix some dragging issues with XWayland
# windowrule = nofocus, match:class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
