# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      ██████╗  ██████╗██╗  ██╗
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔═══██╗██╔════╝██║ ██╔╝
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ██║   ██║██║     █████╔╝ 
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██║   ██║██║     ██╔═██╗ 
# ██║  ██║   ██║   ██║     ██║  ██║███████╗╚██████╔╝╚██████╗██║  ██╗
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝


source = ~/.local/state/my-current-theme/hyprlock.conf
auth {
  pam {
    enabled = true
    module = hyprlock
  }
  fingerprint {
    enabled = true
    ready_message = Scan fingerprint
    present_message = Scanning...
  }
}
background {
  monitor =
  path = ~/.local/state/my-current-theme/hyprlock-bg.png
  color = $base
}
# Clock
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 120
  font_family = JetBrainsMono Nerd Font
  position = 0, 375
  halign = center
  valign = center
}
# Username
label {
  monitor =
  text = $USER
  color = $text
  font_size = 30
  font_family = JetBrainsMono Nerd Font
  position = 0, 225
  halign = center
  valign = center
}
input-field {
  monitor =
  size = 750, 120
  outline_thickness = 4
  outer_color = $blue
  inner_color = $base_transparent
  font_color = $text
  font_family = JetBrainsMono Nerd Font
  fade_on_empty = false
  placeholder_text = Password Kang 󰈷
  rounding = 0
  check_color = $blue0
  fail_color = $red
  fail_text = <i>$FAIL ($ATTEMPTS)</i>
  capslock_color = $yellow
  position = 0, -325
  halign = center
  valign = center
}
# Fingerprint status
label {
  monitor =
  text = $FPRINTPROMPT
  color = $text
  font_size = 20
  font_family = JetBrainsMono Nerd Font
  position = 0, -425
  halign = center
  valign = center
}
