#!/usr/bin/env bash

clang++ -std=c++17 -Werror -Wall -Wextra -Wshadow -Wconversion -Wnull-dereference -Wnon-virtual-dtor -Woverloaded-virtual -Wold-style-cast -pedantic-errors -O0 -g3 -fsanitize=address,undefined "$@"
