#!/usr/bin/env bash

# Check if at least one argument is provided
if [ $# -lt 1 ]; then
  echo "Usage: $0 arg1 [arg2 ... argN]"
  exit 1
fi

# Group all arguments except the last
opts=("${@:1:$#-1}")
# The last argument
target="${!#}"

feh --geometry 800x600 --scale-down --image-bg black "${opts[@]}" --start-at "$target"

# INFO: OPTS
# -F | --fullscreen
# -z | --randomize
