# 00-template.conf - Template for TLP drop-in customizations
# See full explanation: https://linrunner.de/tlp/settings
#
# PARAMETER="value"
# PARAMETER+="add value"
START_CHARGE_THRESH_BAT0=75
STOP_CHARGE_THRESH_BAT0=95

START_CHARGE_THRESH_BAT1=75
STOP_CHARGE_THRESH_BAT1=95
