hl.on("hyprland.start", function()
	local x = hl.exec_cmd

	x("/usr/lib/xdg-desktop-portal -r")
	-- x("systemctl --user start hyprpolkitagent")
	x("hypridle")
	x("hyprpaper")
	x("swaync")
	x("waybar")
	x("swayosd-server")
	x("systemctl --user restart elephant.service")
	-- x("elephant")
	x("walker --gapplication-service")
	x("sleep 2 && nm-applet --indicator")
end)
