# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

# https://yazi-rs.github.io/docs/tips/#grid-view
[[mgr.prepend_keymap]]
on = "<C-g>"
run = 'shell -- rofi -theme fullscreen-preview -show filebrowser -filebrowser-command "ya emit reveal" -filebrowser-directory "$(pwd)"'
desc = "Grid view"

# https://yazi-rs.github.io/docs/tips/#drag-and-drop
[[mgr.prepend_keymap]]
on = "<C-n>"
run = '''
	shell 'dragon-drop -x -i -A -T "$@"'
'''
desc = "Drag and drop via dragon"

[[mgr.prepend_keymap]]
on = "<S-n>"
run = "shell 'nautilus \"$@\"' --args '%d'"
desc = "Open GUI file manager here"

[[mgr.prepend_keymap]]
on = "!"
run = 'shell --orphan --confirm kitty'
desc = "Open terminal here"

# dedukun/bookmarks
[[mgr.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"
[[mgr.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"
[[mgr.prepend_keymap]]
on = ["m", "a"]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"
[[mgr.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

# https://github.com/ndtoan96/ouch.yazi#compression
[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch 7z"
desc = "Compress with ouch"

# yazi-rs/plugins:smart-filter
[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = "H"
run = "tab_switch -1 --relative"
desc = "Switch to the previous tab"
[[mgr.prepend_keymap]]
on = "L"
run = "tab_switch 1 --relative"
desc = "Switch to the next tab"

# yazi-rs/plugins:mount
[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"
desc = "Mount manager"

[[mgr.prepend_keymap]]
on = ["R"]
run = "rename --empty=stem --cursor=start"
desc = "Rename (emptied)"

# yazi-rs/plugins:toggle-pane
[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
[[mgr.prepend_keymap]]
on = "U"
run = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

# yazi-rs/plugins:chmod
[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd /run/media/$USER"
desc = "Goto /media/$USER"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = "cd /"
desc = "Goto /"

# yazi-rs/plugins:smart-enter
[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["m", "c"]
run = "shell 'makepdf \"${PWD##*/}.pdf\" --width=1366 -n'"
desc = "Convert images to pdf"

[[mgr.prepend_keymap]]
on = ["m", "r"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"

# https://yazi-rs.github.io/docs/tips/#selected-files-to-clipboard
[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
  "yank",
]
desc = "Copy selected files to the system clipboard while yanking"

# wekauwau/confirm-quit
[[mgr.prepend_keymap]]
on = "q"
run = "plugin confirm-quit"
