[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../src/config/system.ini
include-file = modules.ini

[color]
bg="#eff1f5"
bg_0="#e6e9ef"
fg="#4c4f69"
fg_0="#5c5f77"

magenta="#8839ef"
red="#e64553"
yellow="#df8e1d"
green="#40a02b"
blue="#1e66f5"
arch="#0f94d2"

; rosewater="#dc8a78"
; flamingo="#dd7878"
; pink="#ea76cb"
; red="#d20f39"
; peach="#fe640b"
; teal="#179299"
; sky="#04a5e5"
; sapphire="#209fb5"
; lavender="#7287fd"
; subtext-0="#6c6f85"
; overlay-2="#7c7f93"
; overlay-1="#8c8fa1"
; overlay-0="#9ca0b0"
; surface-2="#acb0be"
; surface-1="#bcc0cc"
; surface-0="#ccd0da"
; crust="#dce0e8"

[bar/aline-bar]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = false

width = 99%
height = 25

offset-x = 0.5%
offset-y = 0

background = ${color.bg}
foreground = ${color.fg}

radius-bottom = 1.0

line-size = 2
line-color = ${color.blue}

border-size = 6px
border-color = ${color.bg}

padding-left = 1
padding-right = 1

module-margin-left = 0
module-margin-right = 0

font-0 = "Inconsolata Semi Condensed Bold:size=11;1"
font-1 = "Font Awesome 6 Free Solid:size=11;3"
font-2 = "Material Design Icons Desktop:size=17;4"
font-3 = "MesloLGS NF:style=Regular:size=17;4"
font-4 = "Font Awesome 6 Free Solid:size=9;3"
font-5 = "Material Design Icons Desktop:size=13;4"

;Modules availables but not active:
;	brightness	xkeyboard
; modules-left = launcher sep bi bspwm bd sep mplayer power
; modules-center = bi date bd
; modules-right = bluetooth sep bi filesystem cpu_bar memory_bar bd sep bi battery pulseaudio network bd sep bi updates bd sep tray
modules-left = launcher sep bi bspwm bd sep title
modules-center =
modules-right = bspm-monocle sep bi temperature cpu_bar memory_bar bd sep-half bi battery0 battery1 network bd sep-half bi date bd

separator =
dim-value = 1.0

;;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
