[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../src/config/system.ini
include-file = modules.ini

[color]
bg="#eff1f5"
bg_0="#e6e9ef"
fg="#4c4f69"
fg_0="#9ca0b0"

magenta="#8839ef"
red="#e64553"
yellow="#df8e1d"
peach="#fe640b"
green="#40a02b"
blue="#1e66f5"
arch="#0f94d2"

; rosewater="#dc8a78"
; flamingo="#dd7878"
; pink="#ea76cb"
; red="#d20f39"
; peach="#fe640b"
; teal="#179299"
; sky="#04a5e5"
; sapphire="#209fb5"
; lavender="#7287fd"
; subtext-0="#6c6f85"
; overlay-2="#7c7f93"
; overlay-1="#8c8fa1"
; overlay-0="#9ca0b0"
; surface-2="#acb0be"
; surface-1="#bcc0cc"
; surface-0="#ccd0da"
; crust="#dce0e8"

[bar/clara-bar]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 100%
height = 27

offset-x = 0
offset-y = 0

background = ${color.bg_0}
foreground = ${color.fg}

line-size = 2
line-color = ${color.blue}

border-size = 0
border-color = ${color.bg}

padding-left = 2
padding-right = 2

; Text
font-0 = "JetBrainsMono:style=Bold:pixelsize=9;3"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=10;3"
font-2 = "Material Design Icons Desktop:size=11;3"
font-3 = "Material Design Icons Desktop:size=15;4"
; Glyphs
font-4 = "MesloLGS NF:style=Regular:pixelsize=17;4"
;dpi = 96

modules-left = launcher sep bspwm sep title
modules-center =
; modules-right = bspm-monocle sep network sep date sep battery0 sep battery1
modules-right = bspm-monocle sep date sep battery0 sep battery1

separator =
dim-value = 1.0

;;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
