[module/launcher]
type = custom/text

label = "󰣇"
label-foreground = ${color.arch}

click-left = OpenApps --reload-bspwm
click-right = RiceSelector

######################################################

[module/sep]
type = custom/text
label = "  "
label-background = ${color.bg}

######################################################

[module/sep-half]
type = custom/text
label = " "
label-background = ${color.bg}

######################################################

[module/bi]
type = custom/text
label = "%{T4}%{T-}"
label-foreground = ${color.bg_0}
label-background = ${color.bg}

[module/bd]
type = custom/text
label = "%{T4}%{T-}"
label-foreground = ${color.bg_0}
label-background = ${color.bg}

######################################################

[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true
occupied-scroll = false

ws-icon-0 = 1;%{F#dd7878}%{T3}󰬺%{T-}%{F-}
ws-icon-1 = 2;%{F#ea76cb}%{T3}󰬻%{T-}%{F-}
ws-icon-2 = 3;%{F#8839ef}%{T3}󰬼%{T-}%{F-}
ws-icon-3 = 4;%{F#e64553}%{T3}󰬽%{T-}%{F-}
ws-icon-4 = 5;%{F#df8e1d}%{T3}󰬾%{T-}%{F-}
ws-icon-5 = 6;%{F#04a5e5}%{T3}󰬿%{T-}%{F-}
ws-icon-default = "♟ "

format = <label-state>

label-focused = "󰧞"
label-focused-font = 3
label-focused-background = ${color.bg_0}
label-focused-foreground = ${color.blue}

label-occupied = "󰧞"
label-occupied-font = 3
label-occupied-background = ${color.bg_0}
label-occupied-foreground= ${color.fg}

label-empty = %icon%
label-empty-background = ${color.bg_0}
label-empty-foreground = ${color.fg}

label-separator = " "
label-separator-background = ${color.bg_0}

######################################################

[module/title]
type = internal/xwindow

format = <label>
; format-prefix = "󱂬 "
; format-prefix-foreground = ${color.red}

label = %title%
label-maxlen = 70
label-foreground = ${color.fg}

label-empty = "Arch Linux"
label-empty-foreground = ${color.fg_0_0}

######################################################

[module/bspm-monocle]
type = custom/script
exec = ~/.config/bspwm/src/bspm-indicator
tail = true
label-foreground = ${color.fg}

######################################################

[module/temperature]
type = internal/temperature

format = <label>
format-prefix = "🌡 "
format-prefix-font = 2
format-prefix-background = ${color.mb}
format-prefix-foreground = ${color.yellow}

label = %temperature-c%
label-background = ${color.mb}

format-warn = <label-warn>
format-warn-prefix = "🌡 "
format-warn-prefix-font = 2
format-warn-prefix-background = ${color.mb}
format-warn-prefix-foreground = ${color.red}

label-warn = %temperature-c%ooking!
label-warn-background = ${color.mb}
label-warn-foreground = ${color.red}

; Seconds to sleep between updates
; Default: 1
interval = 3

; Thermal zone to use
; To list all the zone types, run 
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 1


; Base temperature for where to start the ramp (in degrees celsius)
; Default: 0
base-temperature = 35

; Threshold temperature to display warning label (in degrees celsius)
; Default: 80
warn-temperature = 60

######################################################

[module/memory_bar]
type = internal/memory
interval = 3

format = <label>
format-prefix = " "
format-prefix-background = ${color.bg_0}
format-prefix-foreground = ${color.yellow}

label = "%used%"
label-background = ${color.bg_0}

#####################################################

[module/battery0]
type = internal/battery
full-at = 99
battery = ${system.sys_battery0}
adapter = ${system.sys_adapter}
poll-interval = 3
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-charging-background = ${color.bg_0}
label-charging = " %percentage%%  "

format-discharging = <ramp-capacity><label-discharging>
format-discharging-background = ${color.bg_0}
label-discharging = " %percentage%%  "

format-full = <label-full>
format-full-prefix = ""
format-full-prefix-font = 2
format-full-background = ${color.bg_0}
format-full-prefix-foreground = ${color.green}
label-full = " %percentage%%  "

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${color.blue}
ramp-capacity-font = 2

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${color.green}
animation-charging-font = 2
animation-charging-framerate = 700

######################################################

[module/battery1]
type = internal/battery
full-at = 99
battery = ${system.sys_battery1}
adapter = ${system.sys_adapter}
poll-interval = 3
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-charging-background = ${color.bg_0}
label-charging = " %percentage%%  "

format-discharging = <ramp-capacity><label-discharging>
format-discharging-background = ${color.bg_0}
label-discharging = " %percentage%%  "

format-full = <label-full>
format-full-prefix = ""
format-full-prefix-font = 2
format-full-background = ${color.bg_0}
format-full-prefix-foreground = ${color.green}
label-full = " %percentage%%  "

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${color.blue}
ramp-capacity-font = 2

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${color.green}
animation-charging-font = 2
animation-charging-framerate = 700

######################################################

[module/network]
type = internal/network
interface = ${system.sys_network_interface}

interval = 3
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = " "
format-connected-prefix-background = ${color.bg_0}
format-connected-prefix-foreground = ${color.green}

speed-unit = ""
label-connected = "%{A1:OpenApps --netmanager:}%downspeed%%{A}"
label-connected-background = ${color.bg_0}

format-disconnected = <label-disconnected>
format-disconnected-prefix = ""
format-disconnected-prefix-background = ${color.bg_0}
format-disconnected-prefix-foreground = ${color.red}

label-disconnected = "%{A1:OpenApps --netmanager:}Offline%{A}"
label-disconnected-background = ${color.bg_0}

######################################################

[module/date]
type = internal/date
interval = 3

time = "%I:%M %P"
;;date-alt = " %A, %d %B %Y"
format = <label>
; format-prefix = ""


label = "%{A1:OpenApps --calendar:}%time%%{A}"
label-background = ${color.bg_0}

######################################################

[module/filesystem]
type = internal/fs
mount-0 = /

interval = 60
fixed-values = false

format-mounted = <label-mounted>
format-mounted-prefix = ""
format-mounted-prefix-background = ${color.mc}
format-mounted-prefix-foreground = ${color.purple}

format-unmounted = <label-unmounted>
format-unmounted-prefix = ""
format-unmounted-prefix-background = ${color.mc}
format-unmounted-prefix-foreground = ${color.purple}

label-mounted = "%used%"
label-mounted-padding = 1
label-mounted-background = ${color.mc}

label-unmounted = %mountpoint%: not mounted
label-unmounted-padding = 1
label-unmounted-background = ${color.mc}

######################################################

[module/pulseaudio]
type = internal/pulseaudio

;;sink = alsa_output.pci-0000_00_1b.0.analog-stereo
use-ui-max = true
interval = 5
;;<bar-volume>
format-volume = <label-volume>
format-volume-prefix = ""
format-volume-prefix-foreground = ${color.blue}
format-volume-background = ${color.mc}

label-volume = "%percentage%"
label-volume-padding = 1

format-muted = <label-muted>
format-muted-background = ${color.mc}
format-muted-prefix = ""
format-muted-prefix-foreground = ${color.blue}
label-muted = "Muted"
label-muted-padding = 1
label-muted-foreground = ${color.red}

click-right = OpenApps --soundcontrol

######################################################

[module/brightness]
type = internal/backlight
card = ${system.sys_graphics_card}

enable-scroll = false

format = <ramp><label>
label = "%percentage%%"
label-padding = 2 pt

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-font = 2
ramp-foreground = ${color.yellow}

######################################################

[module/mplayer]
type = custom/text
label = ""
label-font = 5
label-padding = 8 pt
label-background = ${color.bg}
label-foreground = ${color.fg}

click-left = OpenApps --player
click-right = OpenApps --music

[module/power]
type = custom/text
label = ""
label-font = 5
label-background = ${color.bg}
label-foreground = ${color.fg}

click-left = OpenApps --powermenu

######################################################

[module/tray]
type = internal/tray

format = <tray>
format-background = ${color.bg}
tray-background = ${color.bg}
tray-foreground = ${color.fg}
tray-spacing = 8px
tray-padding = 0px
tray-size = 60%

#####################################################

[module/bluetooth]
type = custom/script
exec = ~/.config/bspwm/src/bluetooth.sh
interval = 3

format = <label>
format-font = 6
label = "%output%"
click-left = OpenApps --bluetooth

#####################################################

[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock

format = <label-layout>
format-background = ${color.mc}
format-prefix = " "
format-prefix-font = 2
format-prefix-foreground = ${color.cyan}

label-layout = %{A1:OpenApps --keyboard:}%layout%%{A}

######################################################
