#!/bin/bash

# Check if at least one argument is provided
if [ $# -lt 1 ]; then
  echo "Usage: $0 [options] <file/dir>"
  exit 1
fi

# Group all arguments except the last
options=("${@:1:$#-1}")
# The last argument
target="${!#}"

# feh --geometry 800x600 --scale-down --image-bg black --sort filename "${options[@]}" "$target"
feh --geometry 800x600 \
    --scale-down \
    --image-bg black \
    --sort filename \
    --action 'basename "%f" | wl-copy' \
    "${options[@]}" "$target"
# feh --geometry 800x600 --scale-down --image-bg black --sort filename --action 'basename "%f" | xclip -selection clipboard' "${options[@]}" "$target"

# OPTIONS
# -F | --fullscreen
# -z | --randomize
# --start-at <file>
