#!/bin/bash

CURRENT_THEME_DIR="$HOME/.local/state/my-current-theme"
THEMES_DIR="$HOME/.local/share/my-themes"

menu() {
  local prompt="$1"
  local options="$2"
  local extra="$3"
  local preselect="$4"

  read -r -a args <<<"$extra"

  if [[ -n "$preselect" ]]; then
    local index
    index=$(echo -e "$options" | grep -nxF "$preselect" | cut -d: -f1)
    if [[ -n "$index" ]]; then
      args+=("-c" "$index")
    fi
  fi

  echo -e "$options" | walker --dmenu --width 1366 --height 768 -p "$prompt…" "${args[@]}" 2>/dev/null
}

get_themes() {
  find "$THEMES_DIR/" -mindepth 1 -maxdepth 1 \( -type d -o -type l \) | sort | while read -r path; do
    echo "$(basename "$path")"
  done
}

get_theme_current(){
  basename "$(realpath "$CURRENT_THEME_DIR")"
}

set_theme_gnome(){
  if [[ -f "$CURRENT_THEME_DIR/light.mode" ]]; then
    gsettings set org.gnome.desktop.interface color-scheme "prefer-light"
    gsettings set org.gnome.desktop.interface icon-theme "Papirus-Light"
  else
    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
    gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
  fi

  GTK_THEME_FILE="$CURRENT_THEME_DIR/gtk"
  if [[ -f "$GTK_THEME_FILE" ]]; then
    gsettings set org.gnome.desktop.interface gtk-theme "$(<"$GTK_THEME_FILE")"
  else
    echo "Warning: GTK theme file not found"
  fi
}

set_theme() {
  if [[ -z $1 ]]; then
    echo "Usage: set_theme <theme-name>"
    exit 1
  elif [[ $1 == "CNCLD" ]]; then
    echo "Theme selection cancelled"
    exit 0
  fi

  THEME_PATH="$THEMES_DIR/$1"

  # Check if the theme entered exists
  if [[ ! -d "$THEME_PATH" ]]; then
    echo "Theme '$1' does not exist in $THEMES_DIR"
    exit 1
  fi

  # Update theme symlinks
  ln -nsf "$THEME_PATH" "$CURRENT_THEME_DIR"

  # Restart components to apply new theme
  pgrep -x waybar >/dev/null && killall -SIGUSR2 waybar || waybar & disown
  pkill -x swayosd-server && swayosd-server & disown
  hyprctl reload
  pkill -SIGUSR2 btop
  makoctl reload

  # Kitty
  kitten themes --reload-in=all "$1"
  set_theme_gnome
  # omarchy-theme-set-browser

  notify-send "Theme set to $1"
}

show_theme_menu() {
  theme=$(menu "Theme" "$(get_themes)" "" "$(get_theme_current)")
  set_theme "$theme"
}

show_system_menu() {
  case $(menu "System" "  Lock\n󰤄  Suspend\n󰜉  Restart\n󰐥  Shutdown") in
  *Lock*) pidof hyprlock || hyprlock & ;;
  *Suspend*) systemctl suspend ;;
  *Restart*) systemctl reboot --no-wall ;;
  *Shutdown*) systemctl poweroff --no-wall ;;
  esac
}

go_to_menu() {
  case "${1,,}" in
  *theme*) show_theme_menu ;;
  *system*) show_system_menu ;;
  esac
}

show_error_menu() {
  menu "Error: Need argument"
}

if [[ -n "$1" ]]; then
  BACK_TO_EXIT=true
  go_to_menu "$1"
else
  show_error_menu 
fi
