#!/usr/bin/env bash
set -euo pipefail

mode="${1:-full}"

dir="$HOME/Pictures/screenshots"
mkdir -p "$dir"
file="$dir/$(date +'%Y-%m-%d_%H-%M-%S').png"

case "$mode" in
full)
  cmd=(grim "$file")
  ;;
partial)
  cmd=(grim -g "$(slurp)" "$file")
  ;;
*)
  notify-send -u critical "Unknown screenshot mode"
  exit 1
  ;;
esac

if "${cmd[@]}"; then
  notify-send -u low -i "$file" "Screenshot saved" "$file"
else
  notify-send -u critical "Screenshot failed"
fi
