#!/bin/bash

if [[ -z $1 ]]; then
  echo "Usage: set-theme <theme-name>"
  exit 1
fi

CURRENT_THEME_DIR="$HOME/.local/state/my-current-theme"
THEMES_DIR="$HOME/.local/share/my-themes"
THEME_PATH="$THEMES_DIR/$1"

set_theme_gnome() {
  if [[ -f "$CURRENT_THEME_DIR/light.mode" ]]; then
    gsettings set org.gnome.desktop.interface color-scheme "prefer-light"
    gsettings set org.gnome.desktop.interface icon-theme "Papirus-Light"
  else
    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
    gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
  fi

  GTK_THEME_FILE="$CURRENT_THEME_DIR/gtk"
  if [[ -f "$GTK_THEME_FILE" ]]; then
    THEME_NAME="$(tr -d '\n' <"$GTK_THEME_FILE")"

    # GTK3
    gsettings set org.gnome.desktop.interface gtk-theme "$THEME_NAME"

    # GTK4
    GTK4_SRC="$HOME/.themes/$THEME_NAME/gtk-4.0"
    GTK4_DEST="$HOME/.config/gtk-4.0"

    if [[ -d "$GTK4_SRC" ]]; then
      # Remove old link or directory first
      if [[ -L "$GTK4_DEST" || -d "$GTK4_DEST" ]]; then
        rm -rf "$GTK4_DEST"
      fi

      ln -sf "$GTK4_SRC" "$GTK4_DEST"

    else
      echo "Warning: GTK4 directory not found for theme '$THEME_NAME'"
    fi

  else
    echo "Warning: GTK theme file not found"
  fi
}

# Check if the theme entered exists
if [[ ! -d "$THEME_PATH" ]]; then
  echo "Theme '$1' does not exist in $THEMES_DIR"
  exit 1
fi

# Update theme symlinks
ln -nsf "$THEME_PATH" "$CURRENT_THEME_DIR"

# Restart components to apply new theme
pgrep -x waybar >/dev/null && killall -SIGUSR2 waybar || waybar &
disown
pkill -x swayosd-server && swayosd-server &
disown
hyprctl reload
pkill -SIGUSR2 btop
makoctl reload

# Kitty
kitten themes --reload-in=all "$1"
set_theme_gnome
# omarchy-theme-set-browser

notify-send "Theme set to $1"
