return {
  {
    "stevearc/conform.nvim",
    opts = {
      formatters = {
        sqlfluff = {
          command = "sqlfluff",
          args = {
            "fix",
            "--disable-progress-bar",
            "--stdin-filename",
            "$FILENAME",
            "-",
          },
          stdin = true,
        },
      },
      formatters_by_ft = {
        blade = { "pint" },
        c = { "clang-format" },
        cmake = { "gersemi" },
        cpp = { "clang-format" },
        css = { "prettier" },
        fish = { "fish_indent" },
        html = { "prettier" },
        javascript = { "prettier" },
        javascriptreact = { "prettier" },
        json = { "prettier" },
        jsonc = { "prettier" },
        lua = { "stylua" },
        markdown = { "prettier" },
        php = { "pint", "php_cs_fixer" },
        rust = { "rustfmt" },
        scss = { "prettier" },
        sh = { "shfmt" },
        -- sql = { "pg_format" },
        sql = { "sqlfluff" },
        typescript = { "prettier" },
        typescriptreact = { "prettier" },
        vue = { "prettier" },
        yaml = { "prettier" },
      },
    },
  },
}
